[project]
name = "asr"
version = "0.1.0"
description = "Automatic speech recognition for Polish spoken words"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.13.0",
    "matplotlib>=3.10.8",
    "protobuf>=7.35.0",
    "scipy>=1.17.1",
    "sentencepiece>=0.2.1",
    "sounddevice>=0.5.5",
    "torch>=2.11.0",
    "torchaudio>=2.11.0",
    "torchmetrics>=1.9.0",
    "transformers>=4.46,<5",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "ruff>=0.15.11",
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cu126" }]
torchvision = [{ index = "pytorch-cu126" }]
torchaudio = [{ index = "pytorch-cu126" }]

[build-system]
requires = ["uv_build>=0.11.7,<0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
module-name = "src"
